apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-operator@sha256:abb94e6f3aecce7964f0c1440c2dc423ca669b92d189a028576e5dd311cc8dd1
        name: container-image
        resources: {}
status: {}
