apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-oauth@sha256:7c867c18d803b37924c7097f3e15b0d8a611199f197dfe71195694a61f5dbdf1
        name: container-image
        resources: {}
status: {}
