apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-oauth@sha256:16de25ca064ca149339e605dd0ca56732c8a3d6f163d44fb8c723d7ffdb71acc
        name: container-image
        resources: {}
status: {}
