apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-oauth@sha256:c155e88e28707afc0746b7f486824b2896f9f3e90a44c082c79925fc5635882c
        name: container-image
        resources: {}
status: {}
