apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth
    app.kubernetes.io/part-of: spi
  name: spi-oauth
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: spi-oauth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: spi-oauth
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-oauth@sha256:a8de4725ad3261b8087c5700a8945ffa20014f6dcd50ac8228fe2b66447aa403
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
